version: "3.9"

services:
  api:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis
    environment:
      PORT: 8080
      DB_URL: postgres://postgres:pipeit@postgres:5432/pipeit
      REDIS_HOST: redis
      REDIS_PORT: 6379
    command: sh -c "sleep 10 && npm run migrate && npm run start"

  worker:
    build: .
    command: npm run worker
    depends_on:
      - redis
      - postgres
    environment:
      PORT: 8080
      DB_URL: postgres://postgres:pipeit@postgres:5432/pipeit
      REDIS_HOST: redis
      REDIS_PORT: 6379

  postgres:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: pipeit
      POSTGRES_DB: pipeit
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    ports:
      - "6379:6379"
